cmake: check libva-x11 instead of X11
This fixes the error below when X11 is not available

In file included from
/home/xhh/graphics/ex/vaapi/media-driver/media_driver/linux/common/ddi/media_libva.cpp:47:
/home/xhh/graphics/ex/vaapi/media-driver/media_driver/linux/common/ddi/media_libva_putsurface_linux.h:31:10:
fatal error: va/va_dricommon.h: No such file or directory
 #include <va/va_dricommon.h>