Add missing headers for C++23
Add headers to resolve C++23 build errors because C++23 removed
transitive includes so you have to add the headers directly.

Errors:
vendor/intel/desktop/media-driver/cmrtlib/agnostic/share/cm_printf_host.cpp:226:43:
error: use of undeclared identifier 'atoi'
  226 |                 m_currToken.tokenString =
atoi(m_currToken.tokenString.c_str());

Signed-off-by: Hirokazu Honda <hiroh@google.com>