[ClearLinux] Fix a bunch of compile issues on ClearLinux (#199)
* [clr] fix -Werror=strict-aliasing compile issue

fix strict-aliasing compile issue as below

    /.../media_vaapi/media-driver/cmrtlib/agnostic/share/cm_printf_host.cpp:629:63: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                         m_args[m_numMultArg - m_argsExpected] = *((int*            )&(header->scalar64));

Signed-off-by: jwang <jing.j.wang@intel.com>

* [clr] fix -Werror=unused-variable compile issues

fix unused-variable compile issues as below
    /.../devel/media_vaapi/media-driver/cmrtlib/agnostic/hardware/cm_device.cpp:328:14: err
or: unused variable ‘tmpQueue’ [-Werror=unused-variable]
         CmQueue *tmpQueue = nullptr;
                  ^~~~~~~~

Signed-off-by: jwang <jing.j.wang@intel.com>

* [clr] fix -Wdelete-non-virtual-dtor issue

fix compile issue as below
    /.../devel/media_vaapi/media-driver/cmrtlib/linux/../agnostic/share/cm_mem.h:31:56: err
or: deleting object of polymorphic class type ‘CmQueue_RT’ which has non-virtual destructor might
cause undefined behavior [-Werror=delete-non-virtual-dtor]

Signed-off-by: jwang <jing.j.wang@intel.com>

* [clr] fix -Werror=re-order compile issue

fix compile issues as below
    /.../devel/media_vaapi/media-driver/cmrtlib/linux/hardware/cm_device.h:179:15: error: ‘CmDevice_RT::m_vaDisplay’ will be initialized after [-Werror=reorder]
         VADisplay m_vaDisplay;
                   ^~~~~~~~~~~
    /.../devel/media_vaapi/media-driver/cmrtlib/linux/hardware/cm_device.h:178:27: error:   ‘VAStatus (* CmDevice_RT::m_fvaCmExtSendReqMsg)(VADisplay, void*, uint32_t*, void*, uint32_t*, uint32_t*, void*, uint32_t*)’ [-Werror=reorder]
         pvaCmExtSendReqMsg    m_fvaCmExtSendReqMsg;

Signed-off-by: jwang <jing.j.wang@intel.com>

* [clr] several compile patch updates

*) move destructor of CmQueue and CmDevice from public to protected
*) fix a error when delete unused variable for vaTerminate(m_vaDisplay)
*) coding style

Signed-off-by: jwang <jing.j.wang@intel.com>